In [190]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [191]:
df = pd.read_csv('SlotPatronRatingsJan2018Mar2018.csv')

In [192]:
df.shape

(3729462, 34)

In [193]:
df.head(10)

,CoinIn,AccountNumber,AssetNumber,CoinOut,AvailableCompPoints,Slot Denomination,TradingDate,HandlePulls,Location,IRSJackpot,...,GameProgressiveGroup,GameOptions,GameBaseTheoPayTable,TimeCreated,DateCreated,DateModified,TimeModified,Age,Gender,MembershipType
0,9419,300024840,21681,2850,6224,1.0,01JAN2018,53,107,969,...,0,0,82.01,3:52:01,02JAN2018,02JAN2018,3:57:59,47,F,A
1,8970,300027357,21767,3970,0,1.0,01JAN2018,180,1705,0,...,0,0,91.64,15:27:02,01JAN2018,01JAN2018,15:39:56,63,F,C
2,4105,300024700,20966,3065,338,1.0,01JAN2018,159,1511,0,...,0,0,88.54,16:21:09,01JAN2018,01JAN2018,16:33:58,56,M,B
3,630,300019112,20158,130,0,1.0,01JAN2018,22,3506,0,...,0,0,0.00,17:54:26,01JAN2018,01JAN2018,17:59:50,72,F,F
4,2380,300024700,20743,2280,338,1.0,01JAN2018,91,705,0,...,0,0,82.01,16:54:59,01JAN2018,01JAN2018,17:02:59,56,M,B
5,3360,300019485,21015,2360,0,1.0,01JAN2018,60,502,0,...,0,0,82.01,14:59:13,01JAN2018,01JAN2018,15:08:12,73,F,D
6,13170,300026898,21658,33500,0,1.0,01JAN2018,89,909,0,...,0,0,78.13,23:49:02,01JAN2018,02JAN2018,0:04:40,58,F,A
7,2050,300024788,20900,183,0,1.0,01JAN2018,82,5106,0,...,0,0,0.00,15:41:51,01JAN2018,01JAN2018,15:53:08,65,M,C
8,49750,300024840,21003,24875,6224,1.0,01JAN2018,157,2502,0,...,0,0,87.87,22:12:17,01JAN2018,01JAN2018,22:23:48,47,F,A
9,34350,300026523,20414,21850,0,1.0,01JAN2018,229,703,2562,...,0,0,82.01,18:56:41,01JAN2018,01JAN2018,19:26:01,46,M,B

In [194]:
df.columns

Index(['CoinIn', 'AccountNumber', 'AssetNumber', 'CoinOut',
       'AvailableCompPoints', 'Slot Denomination', 'TradingDate',
       'HandlePulls', 'Location', 'IRSJackpot', 'LastMonthYearRated',
       'PromoCode', 'RatingCode', 'Remarks', 'TimeStopped', 'Status',
       'TimeStarted', 'TheoCoinIn', 'TheoLoss', 'Zone', 'GameNumber', 'GameID',
       'GameDenomination', 'GameMaxCoinIn', 'GameProgressiveGroup',
       'GameOptions', 'GameBaseTheoPayTable', 'TimeCreated', 'DateCreated',
       'DateModified', 'TimeModified', 'Age', 'Gender', 'MembershipType'],
      dtype='object')

In [195]:
df = df[0:10000]

In [196]:
df1 = df.copy()

In [197]:
df.set_index(['AccountNumber','TradingDate'], inplace= True)

In [198]:
df.head()

,,CoinIn,AssetNumber,CoinOut,AvailableCompPoints,Slot Denomination,HandlePulls,Location,IRSJackpot,LastMonthYearRated,PromoCode,...,GameProgressiveGroup,GameOptions,GameBaseTheoPayTable,TimeCreated,DateCreated,DateModified,TimeModified,Age,Gender,MembershipType
AccountNumber,TradingDate,,,,,,,,,,,,,,,,,,,,,
300024840,01JAN2018,9419,21681,2850,6224,1.0,53,107,969,118,NaN,...,0,0,82.01,3:52:01,02JAN2018,02JAN2018,3:57:59,47,F,A
300027357,01JAN2018,8970,21767,3970,0,1.0,180,1705,0,118,NaN,...,0,0,91.64,15:27:02,01JAN2018,01JAN2018,15:39:56,63,F,C
300024700,01JAN2018,4105,20966,3065,338,1.0,159,1511,0,118,NaN,...,0,0,88.54,16:21:09,01JAN2018,01JAN2018,16:33:58,56,M,B
300019112,01JAN2018,630,20158,130,0,1.0,22,3506,0,118,NaN,...,0,0,0.00,17:54:26,01JAN2018,01JAN2018,17:59:50,72,F,F
300024700,01JAN2018,2380,20743,2280,338,1.0,91,705,0,118,NaN,...,0,0,82.01,16:54:59,01JAN2018,01JAN2018,17:02:59,56,M,B

In [199]:
df.sort_index(inplace=True)

In [200]:
df.head()

                           CoinIn  AssetNumber  CoinOut  AvailableCompPoints  \
AccountNumber TradingDate
300010643     01JAN2018      4784        20326     3080                    0
              01JAN2018      2400        20845     1400                    0
              01JAN2018      7240        20651     6250                    0
              01JAN2018      9484        20327     5415                    0
              01JAN2018      3450        21112     1150                    0

                           Slot Denomination  HandlePulls  Location  \
AccountNumber TradingDate
300010643     01JAN2018                  1.0          158      3303
              01JAN2018                  1.0           40       507
              01JAN2018                  1.0          127      1705
              01JAN2018                  1.0          148      3304
              01JAN2018                  2.0           62      2309

                           IRSJackpot  LastMonthYearRated  PromoCode  \
AccountNumber TradingDate
300010643     01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN

                               ...       GameProgressiveGroup GameOptions  \
AccountNumber TradingDate      ...
300010643     01JAN2018        ...                          1           0
              01JAN2018        ...                          0           0
              01JAN2018        ...                          0           0
              01JAN2018        ...                          1           0
              01JAN2018        ...                          0           0

                           GameBaseTheoPayTable TimeCreated  DateCreated  \
AccountNumber TradingDate
300010643     01JAN2018                   81.85     3:33:09    02JAN2018
              01JAN2018                   87.87    16:36:22    01JAN2018
              01JAN2018                   88.10    16:03:30    01JAN2018
              01JAN2018                   81.50     1:32:35    02JAN2018
              01JAN2018                   82.01     0:17:07    02JAN2018

                           DateModified  TimeModified  Age  Gender  \
AccountNumber TradingDate
300010643     01JAN2018       02JAN2018       3:57:58   46       F
              01JAN2018       01JAN2018      16:40:27   46       F
              01JAN2018       01JAN2018      16:16:07   46       F
              01JAN2018       02JAN2018       1:50:44   46       F
              01JAN2018       02JAN2018       0:22:39   46       F

                          MembershipType
AccountNumber TradingDate
300010643     01JAN2018                D
              01JAN2018                D
              01JAN2018                D
              01JAN2018                D
              01JAN2018                D

[5 rows x 32 columns]

In [201]:
df1.head()

,CoinIn,AccountNumber,AssetNumber,CoinOut,AvailableCompPoints,Slot Denomination,TradingDate,HandlePulls,Location,IRSJackpot,...,GameProgressiveGroup,GameOptions,GameBaseTheoPayTable,TimeCreated,DateCreated,DateModified,TimeModified,Age,Gender,MembershipType
0,9419,300024840,21681,2850,6224,1.0,01JAN2018,53,107,969,...,0,0,82.01,3:52:01,02JAN2018,02JAN2018,3:57:59,47,F,A
1,8970,300027357,21767,3970,0,1.0,01JAN2018,180,1705,0,...,0,0,91.64,15:27:02,01JAN2018,01JAN2018,15:39:56,63,F,C
2,4105,300024700,20966,3065,338,1.0,01JAN2018,159,1511,0,...,0,0,88.54,16:21:09,01JAN2018,01JAN2018,16:33:58,56,M,B
3,630,300019112,20158,130,0,1.0,01JAN2018,22,3506,0,...,0,0,0.00,17:54:26,01JAN2018,01JAN2018,17:59:50,72,F,F
4,2380,300024700,20743,2280,338,1.0,01JAN2018,91,705,0,...,0,0,82.01,16:54:59,01JAN2018,01JAN2018,17:02:59,56,M,B

In [253]:
new_df1 = df1.groupby(['AccountNumber','TradingDate'], sort= True)

In [254]:
df.head()

                           CoinIn  AssetNumber  CoinOut  AvailableCompPoints  \
AccountNumber TradingDate
300010643     01JAN2018      4784        20326     3080                    0
              01JAN2018      2400        20845     1400                    0
              01JAN2018      7240        20651     6250                    0
              01JAN2018      9484        20327     5415                    0
              01JAN2018      3450        21112     1150                    0

                           Slot Denomination  HandlePulls  Location  \
AccountNumber TradingDate
300010643     01JAN2018                  1.0          158      3303
              01JAN2018                  1.0           40       507
              01JAN2018                  1.0          127      1705
              01JAN2018                  1.0          148      3304
              01JAN2018                  2.0           62      2309

                           IRSJackpot  LastMonthYearRated  PromoCode  \
AccountNumber TradingDate
300010643     01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN
              01JAN2018             0                 118        NaN

                               ...       GameProgressiveGroup GameOptions  \
AccountNumber TradingDate      ...
300010643     01JAN2018        ...                          1           0
              01JAN2018        ...                          0           0
              01JAN2018        ...                          0           0
              01JAN2018        ...                          1           0
              01JAN2018        ...                          0           0

                           GameBaseTheoPayTable TimeCreated  DateCreated  \
AccountNumber TradingDate
300010643     01JAN2018                   81.85     3:33:09    02JAN2018
              01JAN2018                   87.87    16:36:22    01JAN2018
              01JAN2018                   88.10    16:03:30    01JAN2018
              01JAN2018                   81.50     1:32:35    02JAN2018
              01JAN2018                   82.01     0:17:07    02JAN2018

                           DateModified  TimeModified  Age  Gender  \
AccountNumber TradingDate
300010643     01JAN2018       02JAN2018       3:57:58   46       F
              01JAN2018       01JAN2018      16:40:27   46       F
              01JAN2018       01JAN2018      16:16:07   46       F
              01JAN2018       02JAN2018       1:50:44   46       F
              01JAN2018       02JAN2018       0:22:39   46       F

                          MembershipType
AccountNumber TradingDate
300010643     01JAN2018                D
              01JAN2018                D
              01JAN2018                D
              01JAN2018                D
              01JAN2018                D

[5 rows x 32 columns]

In [255]:
new_df1.first()

,,CoinIn,AssetNumber,CoinOut,AvailableCompPoints,Slot Denomination,HandlePulls,Location,IRSJackpot,LastMonthYearRated,PromoCode,...,GameProgressiveGroup,GameOptions,GameBaseTheoPayTable,TimeCreated,DateCreated,DateModified,TimeModified,Age,Gender,MembershipType
AccountNumber,TradingDate,,,,,,,,,,,,,,,,,,,,,
300010643,01JAN2018,4784,20326,3080,0,1.0,158,3303,0,118,NaN,...,1,0,81.85,3:33:09,02JAN2018,02JAN2018,3:57:58,46,F,D
300010751,01JAN2018,5160,20439,2798,0,1.0,172,1104,0,118,NaN,...,0,0,85.19,17:53:35,01JAN2018,01JAN2018,18:30:12,70,F,D
300010806,01JAN2018,7480,20897,5640,0,1.0,302,5103,13713,118,NaN,...,0,0,0.00,17:35:48,01JAN2018,01JAN2018,18:13:50,64,F,C
300010986,01JAN2018,79950,20476,68150,0,1.0,533,1313,0,118,NaN,...,0,0,0.00,14:19:49,01JAN2018,01JAN2018,15:03:36,59,NaN,C
300011124,01JAN2018,1250,22060,526,656,1.0,50,2305,0,118,NaN,...,0,0,89.75,17:22:10,01JAN2018,01JAN2018,17:29:32,58,F,B
300012072,01JAN2018,2845,20351,1880,0,1.0,95,108,0,118,NaN,...,0,0,87.87,20:14:32,01JAN2018,01JAN2018,20:18:41,46,F,B
300012104,01JAN2018,79728,21446,63128,0,1.0,660,2506,2939,118,NaN,...,0,0,0.00,13:11:51,01JAN2018,01JAN2018,14:35:37,75,F,B
300012171,01JAN2018,15048,21349,17583,0,1.0,123,303,0,118,NaN,...,0,0,0.00,0:22:12,02JAN2018,02JAN2018,0:36:10,70,F,C
300013023,01JAN2018,8530,20089,7920,0,1.0,1211,1911,0,118,NaN,...,0,0,91.99,21:52:59,01JAN2018,02JAN2018,0:15:57,70,M,E
300013039,01JAN2018,2640,20090,2240,0,1.0,247,1912,0,118,NaN,...,0,0,91.96,21:21:11,01JAN2018,01JAN2018,22:14:22,63,F,E
300013166,01JAN2018,525,21676,215,0,1.0,39,104,0,118,NaN,...,0,0,78.13,19:44:47,01JAN2018,01JAN2018,19:49:22,59,NaN,E
300013181,01JAN2018,3432,20359,4455,0,1.0,117,306,0,118,NaN,...,0,0,87.87,16:45:23,01JAN2018,01JAN2018,17:07:34,69,F,F
300014362,01JAN2018,1627,20067,1225,2179,1.0,105,705,0,118,NaN,...,0,0,82.01,23:22:24,01JAN2018,01JAN2018,23:32:05,60,M,B
300014363,01JAN2018,3950,20066,950,7949,1.0,32,704,0,118,NaN,...,0,0,82.01,20:52:16,01JAN2018,01JAN2018,20:55:08,57,M,A
300014424,01JAN2018,6340,20436,1744,0,1.0,122,1101,0,118,NaN,...,0,0,85.19,18:53:03,01JAN2018,01JAN2018,19:03:41,61,M,B
300014425,01JAN2018,14,21048,60,0,1.0,2,508,0,118,NaN,...,0,0,82.01,21:15:39,01JAN2018,01JAN2018,21:30:55,60,F,B
300014485,01JAN2018,8726,20187,3835,6,1.0,233,2902,0,118,NaN,...,0,0,82.01,18:49:52,01JAN2018,01JAN2018,19:12:25,76,F,C
300014486,01JAN2018,63,21186,0,0,1.0,3,101,0,118,NaN,...,0,0,87.87,17:20:43,01JAN2018,01JAN2018,17:22:53,77,M,D
300014520,01JAN2018,1634,20545,634,0,1.0,71,907,0,118,NaN,...,0,224,91.54,19:17:56,01JAN2018,01JAN2018,19:21:34,55,M,B
300014828,01JAN2018,1050,20560,2577,0,1.0,35,1302,0,118,NaN,...,0,0,92.04,23:24:58,01JAN2018,01JAN2018,23:29:51,51,F,D
300014833,01JAN2018,3420,20562,1272,0,1.0,81,1304,0,118,NaN,...,0,0,92.04,1:28:50,02JAN2018,02JAN2018,1:36:00,49,M,C
300014839,01JAN2018,13500,22214,13054,0,1.0,100,509,0,118,NaN,...,0,0,90.25,22:58:54,01JAN2018,01JAN2018,23:09:15,59,F,B
300014876,01JAN2018,3490,20912,1010,0,1.0,64,1504,0,118,NaN,...,0,0,0.00,17:26:04,01JAN2018,01JAN2018,17:31:42,68,F,C
300015254,01JAN2018,510,21212,5,0,1.0,17,3506,0,118,NaN,...,0,0,88.53,23:20:49,01JAN2018,01JAN2018,23:22:59,65,F,D
300015355,01JAN2018,18875,21654,7870,0,1.0,456,901,0,118,NaN,...,0,0,78.13,22:11:06,01JAN2018,01JAN2018,22:38:08,57,F,E
300015414,01JAN2018,540,20549,540,0,1.0,20,1103,0,118,NaN,...,1,0,81.92,17:46:41,01JAN2018,01JAN2018,17:50:18,70,M,C
300015415,01JAN2018,1386,20549,90,0,1.0,32,1103,0,118,NaN,...,1,0,81.92,17:50:53,01JAN2018,01JAN2018,17:55:15,66,F,C
300015450,01JAN2018,642,21062,395,0,1.0,46,4102,0,118,NaN,...,0,0,88.53,20:10:10,01JAN2018,01JAN2018,20:16:14,69,F,C
300015451,01JAN2018,1350,20046,455,0,1.0,27,4908,0,118,NaN,...,0,0,91.99,19:13:20,01JAN2018,01JAN2018,19:16:59,57,F,B
300015472,01JAN2018,5050,21916,2394,0,1.0,81,307,0,118,NaN,...,0,0,92.09,20:52:04,01JAN2018,01JAN2018,20:59:31,56,F,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300199479,01JAN2018,160,21989,65,22,1.0,20,4108,0,118,NaN,...,0,192,86.30,6:01:47,01JAN2018,01JAN2018,6:06:02,53,M,B
300199792,01JAN2018,3305,21834,667,0,1.0,86,2907,0,118,NaN,...,0,0,88.59,17:12:18,01JAN2018,01JAN2018,17:20:48,82,F,E
300200377,01JAN2018,10738,21190,10568,1,1.0,702,105,0,118,NaN,...,0,0,0.00,16:35:13,01JAN2018,01JAN2018,17:45:38,62,F,D
300200380,01JAN2018,383,20108,80,0,1.0,26,106,0,118,NaN,...,0,0,78.13,14:58:42,01JAN2018,01JAN2018,15:01:27,26,F,D
300200483,01JAN2018,500,20194,0,0,1.0,5,2909,0,118,NaN,...,0,0,82.01,17:02:47,01JAN2018,01JAN2018,17:05:26,65,F,E
300200502,01JAN2018,1941,21207,2690,0,1.0,88,1704,0,118,NaN,...,0,0,90.01,21:52:45,01JAN2018,01JAN2018,22:12:13,43,M,C
300200570,01JAN2018,1900,20633,948,0,1.0,38,3303,0,118,NaN,...,0,0,91.99,22:01:16,01JAN2018,01JAN2018,22:23:55,32,M,C
300200737,01JAN2018,780,21338,426,0,1.0,32,708,0,118,NaN,...,0,0,0.00,14:43:44,01JAN2018,01JAN2018,14:46:23,42,F,C
300200838,01JAN2018,1096,21090,110,0,1.0,37,5504,0,118,NaN,...,0,0,82.97,19:35:19,01JAN2018,01JAN2018,19:40:52,66,F,D
300200861,01JAN2018,1973,21665,975,0,1.0,74,106,0,118,NaN,...,0,0,78.13,0:59:12,02JAN2018,02JAN2018,1:07:12,45,F,E
300200921,01JAN2018,35175,21145,10175,0,5.0,55,1902,0,118,NaN,...,0,0,0.00,1:27:18,02JAN2018,02JAN2018,1:33:55,37,M,A
300201135,01JAN2018,127932,21968,95863,0,1.0,617,506,7069,118,NaN,...,1,0,81.80,20:17:57,01JAN2018,01JAN2018,21:15:44,56,M,A
300201541,01JAN2018,5550,20447,8251,4,1.0,170,1112,0,118,NaN,...,0,0,85.19,23:13:13,01JAN2018,02JAN2018,0:00:04,56,M,C
300201596,01JAN2018,2160,21911,187,0,1.0,14,3106,0,118,NaN,...,0,0,88.56,21:09:29,01JAN2018,01JAN2018,21:11:15,63,F,B
300201676,01JAN2018,434,21644,255,407,1.0,13,1901,0,118,NaN,...,1,0,81.85,0:39:24,02JAN2018,02JAN2018,0:40:31,51,M,H
300201680,01JAN2018,7484,21835,7655,33,1.0,176,2910,0,118,NaN,...,0,0,88.59,18:09:05,01JAN2018,01JAN2018,18:37:05,54,M,D
300201919,01JAN2018,2120,20955,715,0,1.0,37,504,0,118,NaN,...,0,0,93.37,19:10:34,01JAN2018,01JAN2018,19:17:11,41,M,B
300202043,01JAN2018,7550,22272,8730,0,1.0,121,502,0,118,NaN,...,0,0,89.75,15:19:45,01JAN2018,01JAN2018,15:28:17,50,M,A
300202120,01JAN2018,503500,21305,353000,0,1.0,640,1101,0,118,NaN,...,0,224,94.96,22:49:32,01JAN2018,01JAN2018,23:27:38,50,M,A
300202794,01JAN2018,484,21642,355,748,1.0,38,2101,0,118,NaN,...,1,0,81.85,4:20:16,02JAN2018,02JAN2018,4:24:40,32,F,D
300203235,01JAN2018,3460,20632,2252,0,1.0,116,3302,0,118,NaN,...,0,0,92.00,2:15:02,02JAN2018,02JAN2018,2:26:35,44,F,C
300203237,01JAN2018,570,22249,70,0,1.0,24,710,0,118,NaN,...,0,0,89.75,0:02:20,02JAN2018,02JAN2018,0:04:48,43,F,B
300203752,01JAN2018,11616,20676,8490,613,1.0,44,2507,0,118,NaN,...,1,0,81.50,14:30:54,01JAN2018,01JAN2018,14:35:42,37,M,C
300204362,01JAN2018,1031,21035,175,169,1.0,37,2106,0,118,NaN,...,0,0,82.01,21:35:05,01JAN2018,01JAN2018,21:40:10,32,F,C
300204409,01JAN2018,1300,22066,384,102,1.0,22,1907,0,118,NaN,...,0,0,89.75,17:45:21,01JAN2018,01JAN2018,17:48:02,69,M,C
300204756,01JAN2018,1400,20620,426,23,1.0,28,4706,0,118,NaN,...,0,0,87.62,18:50:20,01JAN2018,01JAN2018,18:54:36,52,M,D
300204763,01JAN2018,7285,20741,4285,0,1.0,61,703,0,118,NaN,...,0,0,82.01,10:54:38,01JAN2018,01JAN2018,10:59:25,85,F,B
300204946,01JAN2018,24954,21972,15246,21,1.0,156,1310,1601,118,NaN,...,1,0,81.80,14:04:39,01JAN2018,01JAN2018,14:20:05,65,M,B
300204957,01JAN2018,2580,20892,1090,0,1.0,43,912,0,118,NaN,...,0,0,0.00,19:33:43,01JAN2018,01JAN2018,19:36:35,68,M,B
300207231,01JAN2018,3275,20475,290,12,1.0,28,1312,0,118,NaN,...,0,0,0.00,5:55:14,02JAN2018,02JAN2018,5:59:12,50,M,C

In [256]:
new_df1.groups

{(300010643,
  '01JAN2018'): Int64Index([ 562,  601,  618,  623,  630,  647,  669,  689,  704,  720,  741,
              770,  790,  801,  817,  825,  830,  864,  903,  934,  966,  977,
             1045, 1069, 1070],
            dtype='int64'),
 (300010751,
  '01JAN2018'): Int64Index([800, 803, 883, 1032, 1063], dtype='int64'),
 (300010806,
  '01JAN2018'): Int64Index([ 558,  570,  600,  626,  645,  670,  681,  700,  710,  748,  753,
              758,  853,  858,  867,  868,  876,  892,  894,  899,  969,  976,
             1049, 1051, 1056, 1089],
            dtype='int64'),
 (300010986,
  '01JAN2018'): Int64Index([708, 823, 1085, 1091, 1099, 1104], dtype='int64'),
 (300011124, '01JAN2018'): Int64Index([944], dtype='int64'),
 (300012072,
  '01JAN2018'): Int64Index([ 568,  574,  584,  592,  660,  672,  680,  733,  757,  762,  780,
              796,  820,  881,  910,  928, 1023, 1075],
            dtype='int64'),
 (300012104, '01JAN2018'): Int64Index([794, 886, 1101], dtype='int64'),
 (300012171,
  '01JAN2018'): Int64Index([564, 605, 631, 693, 744, 804, 835, 913, 921, 954, 984, 1027, 1034], dtype='int64'),
 (300013023, '01JAN2018'): Int64Index([620, 831], dtype='int64'),
 (300013039, '01JAN2018'): Int64Index([657, 884, 996], dtype='int64'),
 (300013166, '01JAN2018'): Int64Index([792], dtype='int64'),
 (300013181,
  '01JAN2018'): Int64Index([ 566,  588,  594,  666,  719,  824,  873,  978, 1003, 1013, 1015,
             1066, 1074, 1078, 1098],
            dtype='int64'),
 (300014362, '01JAN2018'): Int64Index([604, 854], dtype='int64'),
 (300014363,
  '01JAN2018'): Int64Index([597, 627, 661, 677, 683, 743, 755, 826, 842, 863, 992, 1031], dtype='int64'),
 (300014424,
  '01JAN2018'): Int64Index([ 589,  608,  617,  636,  639,  654,  696,  706,  722,  728,  740,
              767,  777,  785,  808,  847,  901,  905,  912,  919,  964, 1039,
             1042, 1043, 1065, 1081, 1097],
            dtype='int64'),
 (300014425,
  '01JAN2018'): Int64Index([569, 643, 694, 760, 768, 828, 887, 900, 923, 951, 1059, 1093], dtype='int64'),
 (300014485, '01JAN2018'): Int64Index([573, 774, 776, 1011], dtype='int64'),
 (300014486, '01JAN2018'): Int64Index([686, 705, 967], dtype='int64'),
 (300014520,
  '01JAN2018'): Int64Index([ 578,  622,  673,  730,  754,  784,  816,  829,  837,  855,  869,
              895,  898,  916,  953,  972, 1037, 1057],
            dtype='int64'),
 (300014828,
  '01JAN2018'): Int64Index([577, 655, 707, 805, 811, 844, 995], dtype='int64'),
 (300014833,
  '01JAN2018'): Int64Index([ 635,  642,  658,  674,  684,  702,  712,  745,  752,  775,  778,
              822,  851,  920,  926,  956,  975, 1002, 1012, 1035, 1088, 1090],
            dtype='int64'),
 (300014839,
  '01JAN2018'): Int64Index([ 580,  648,  679,  687,  695,  699,  725,  742,  765,  798,  834,
              859,  893,  947,  960, 1007, 1016, 1030, 1067, 1083],
            dtype='int64'),
 (300014876,
  '01JAN2018'): Int64Index([ 565,  583,  585,  596,  610,  612,  625,  678,  692,  713,  714,
              726,  734,  746,  756,  769,  773,  788,  819,  849,  872,  882,
              907,  911,  927,  948,  957,  959,  961,  980,  988, 1017, 1020,
             1024, 1025, 1041, 1052, 1055, 1062, 1077],
            dtype='int64'),
 (300015254,
  '01JAN2018'): Int64Index([663, 711, 761, 795, 813, 866, 931, 937, 939, 987, 1008, 1082], dtype='int64'),
 (300015355,
  '01JAN2018'): Int64Index([613, 664, 818, 845, 991, 1064, 1094], dtype='int64'),
 (300015414, '01JAN2018'): Int64Index([1036], dtype='int64'),
 (300015415, '01JAN2018'): Int64Index([857, 1009], dtype='int64'),
 (300015450, '01JAN2018'): Int64Index([690, 789], dtype='int64'),
 (300015451,
  '01JAN2018'): Int64Index([634, 716, 751, 946, 1022, 1071, 1080], dtype='int64'),
 (300015472,
  '01JAN2018'): Int64Index([590, 652, 667, 732, 779, 832, 841, 904, 917, 968, 974, 999], dtype='int64'),
 (300015810,
  '01JAN2018'): Int64Index([ 599,  603,  621,  624,  676,  698,  747,  772,  799,  821,  838,
              840,  871,  874,  897,  902,  908,  922,  929,  932,  955, 1004,
             1010, 1019],
            dtype='int64'),
 (300015829,
  '01JAN2018'): Int64Index([738, 763, 764, 815, 924, 925, 933, 971], dtype='int64'),
 (300015851,
  '01JAN2018'): Int64Index([591, 606, 607, 615, 703, 797, 993, 1061], dtype='int64'),
 (300016008,
  '01JAN2018'): Int64Index([ 619,  632,  649,  781,  782,  783,  875,  889,  891,  942,  965,
              982, 1005, 1006, 1060, 1095, 1096],
            dtype='int64'),
 (300016202, '01JAN2018'): Int64Index([997, 1050], dtype='int64'),
 (300016529,
  '01JAN2018'): Int64Index([559, 575, 602, 651, 766, 843, 936, 941, 949, 994, 1058, 1102,
             1103],
            dtype='int64'),
 (300016635,
  '01JAN2018'): Int64Index([ 587,  598,  628,  671,  675,  717,  718,  749,  807,  856,  880,
              940,  970, 1018, 1038, 1054, 1072],
            dtype='int64'),
 (300016660,
  '01JAN2018'): Int64Index([750, 786, 981, 989, 1028, 1053], dtype='int64'),
 (300016763, '01JAN2018'): Int64Index([865], dtype='int64'),
 (300016795, '01JAN2018'): Int64Index([952], dtype='int64'),
 (300016797, '01JAN2018'): Int64Index([709, 915, 979], dtype='int64'),
 (300017367,
  '01JAN2018'): Int64Index([614, 629, 633, 665, 759], dtype='int64'),
 (300017381,
  '01JAN2018'): Int64Index([637, 656, 735, 791, 848, 877, 906, 973, 998, 1044, 1068], dtype='int64'),
 (300017440,
  '01JAN2018'): Int64Index([ 586,  644,  650,  653,  691,  697,  739,  809,  814,  896,  983,
              985,  990, 1000, 1086, 1100, 1105],
            dtype='int64'),
 (300017665,
  '01JAN2018'): Int64Index([609, 638, 729, 812, 860, 909, 914, 1087, 1092], dtype='int64'),
 (300017771,
  '01JAN2018'): Int64Index([616, 646, 836, 1021, 1029, 1040, 1079], dtype='int64'),
 (300017774,
  '01JAN2018'): Int64Index([ 561,  563,  576,  579,  593,  611,  641,  659,  668,  682,  688,
              701,  715,  721,  724,  736,  771,  787,  802,  806,  810,  827,
              833,  852,  878,  885,  888,  890,  938,  943,  950,  958,  963,
              986, 1001, 1026, 1033, 1084],
            dtype='int64'),
 (300017890,
  '01JAN2018'): Int64Index([571, 572, 595, 685, 731, 839, 879, 918, 1014, 1073], dtype='int64'),
 (300017943,
  '01JAN2018'): Int64Index([723, 793, 861, 945, 962, 1046], dtype='int64'),
 (300017980,
  '01JAN2018'): Int64Index([ 560,  567,  581,  582,  640,  662,  727,  846,  850,  862,  870,
              930,  935, 1047, 1048, 1076],
            dtype='int64'),
 (300018013, '01JAN2018'): Int64Index([737], dtype='int64'),
 (300018781, '01JAN2018'): Int64Index([350], dtype='int64'),
 (300019112,
  '01JAN2018'): Int64Index([3, 52, 110, 193, 466, 518], dtype='int64'),
 (300019485,
  '01JAN2018'): Int64Index([5, 15, 139, 207, 242, 265, 297, 325, 337, 417, 531, 549], dtype='int64'),
 (300019488,
  '01JAN2018'): Int64Index([19, 70, 282, 366, 381, 468], dtype='int64'),
 (300019699, '01JAN2018'): Int64Index([309], dtype='int64'),
 (300019974,
  '01JAN2018'): Int64Index([67, 169, 173, 229, 316, 437], dtype='int64'),
 (300020465,
  '01JAN2018'): Int64Index([109, 185, 263, 279, 304, 353, 491, 503, 541], dtype='int64'),
 (300020466, '01JAN2018'): Int64Index([425], dtype='int64'),
 (300020508, '01JAN2018'): Int64Index([147, 196, 459], dtype='int64'),
 (300020566,
  '01JAN2018'): Int64Index([ 10,  14,  65,  69,  85, 100, 128, 164, 182, 189, 197, 201, 218,
             220, 239, 240, 267, 274, 296, 315, 318, 351, 375, 396, 404, 433,
             434, 485, 494, 538, 546, 555],
            dtype='int64'),
 (300021038, '01JAN2018'): Int64Index([344, 362], dtype='int64'),
 (300021763, '01JAN2018'): Int64Index([135], dtype='int64'),
 (300021769, '01JAN2018'): Int64Index([156, 178, 249], dtype='int64'),
 (300023363, '01JAN2018'): Int64Index([101], dtype='int64'),
 (300023883, '01JAN2018'): Int64Index([51, 191], dtype='int64'),
 (300024603,
  '01JAN2018'): Int64Index([ 84, 111, 121, 140, 155, 161, 184, 233, 252, 281, 319, 326, 341,
             364, 371, 392, 424, 467, 484, 488, 522, 543, 548],
            dtype='int64'),
 (300024670, '01JAN2018'): Int64Index([355], dtype='int64'),
 (300024700,
  '01JAN2018'): Int64Index([  2,   4,  23,  27,  36,  43,  44,  62,  71,  87,  93,  94,  98,
             113, 117, 124, 136, 150, 154, 160, 165, 180, 187, 200, 219, 223,
             226, 227, 243, 262, 269, 276, 295, 299, 308, 311, 331, 332, 340,
             342, 358, 374, 382, 393, 416, 439, 458, 462, 481, 495, 507, 514,
             520, 527, 529],
            dtype='int64'),
 (300024746,
  '01JAN2018'): Int64Index([137, 236, 405, 408, 427, 441, 447, 557], dtype='int64'),
 (300024788,
  '01JAN2018'): Int64Index([7, 86, 126, 133, 138, 277, 386, 478, 524], dtype='int64'),
 (300024836,
  '01JAN2018'): Int64Index([38, 134, 163, 168, 216, 287, 348, 372, 383, 421, 430, 463], dtype='int64'),
 (300024840,
  '01JAN2018'): Int64Index([0, 8, 20, 33, 59, 78, 130, 162, 202, 231, 329, 345, 390, 391, 420,
             486, 506],
            dtype='int64'),
 (300024849,
  '01JAN2018'): Int64Index([32, 55, 72, 208, 254, 294, 305, 423, 431, 448], dtype='int64'),
 (300024927,
  '01JAN2018'): Int64Index([74, 103, 118, 120, 141, 360, 457], dtype='int64'),
 (300024971, '01JAN2018'): Int64Index([66, 97, 307], dtype='int64'),
 (300024977,
  '01JAN2018'): Int64Index([40, 64, 152, 235, 255, 397, 428], dtype='int64'),
 (300024981,
  '01JAN2018'): Int64Index([ 34,  46,  47,  81,  82,  92,  95, 107, 144, 213, 292, 365, 473,
             509, 516, 534, 550, 556],
            dtype='int64'),
 (300025568,
  '01JAN2018'): Int64Index([22, 157, 174, 237, 246, 327, 347, 449, 450, 476, 479, 480, 496], dtype='int64'),
 (300025579, '01JAN2018'): Int64Index([314, 335, 349], dtype='int64'),
 (300025604, '01JAN2018'): Int64Index([422], dtype='int64'),
 (300026327,
  '01JAN2018'): Int64Index([ 16, 146, 149, 172, 203, 206, 301, 333, 334, 343, 363, 399, 410,
             446, 461, 471, 499],
            dtype='int64'),
 (300026496,
  '01JAN2018'): Int64Index([39, 127, 131, 158, 177, 181, 241, 454, 483, 511], dtype='int64'),
 (300026523,
  '01JAN2018'): Int64Index([9, 25, 90, 105, 119, 179, 244, 261, 380, 388, 395, 435, 475], dtype='int64'),
 (300026673, '01JAN2018'): Int64Index([56, 104, 273, 465], dtype='int64'),
 (300026727, '01JAN2018'): Int64Index([48, 79, 122, 373], dtype='int64'),
 (300026898,
  '01JAN2018'): Int64Index([6, 143, 310, 317, 322, 328, 369, 377, 385, 418, 444, 477, 482,
             536],
            dtype='int64'),
 (300026945, '01JAN2018'): Int64Index([493], dtype='int64'),
 (300027123, '01JAN2018'): Int64Index([285], dtype='int64'),
 (300027357,
  '01JAN2018'): Int64Index([  1,  28,  35,  75, 114, 209, 224, 234, 238, 260, 266, 272, 278,
             283, 290, 330, 357, 361, 456, 487, 515, 545],
            dtype='int64'),
 (300027528, '01JAN2018'): Int64Index([18, 115, 400, 440], dtype='int64'),
 (300027679, '01JAN2018'): Int64Index([68], dtype='int64'),
 (300027763,
  '01JAN2018'): Int64Index([12, 41, 49, 132, 159, 190, 270, 394], dtype='int64'),
 (300027875, '01JAN2018'): Int64Index([205, 413, 419], dtype='int64'),
 (300028366, '01JAN2018'): Int64Index([77], dtype='int64'),
 (300028656, '01JAN2018'): Int64Index([123], dtype='int64'),
 (300028716, '01JAN2018'): Int64Index([215, 407], dtype='int64'),
 (300029203, '01JAN2018'): Int64Index([31, 232, 502, 532], dtype='int64'),
 (300029820, '01JAN2018'): Int64Index([89], dtype='int64'),
 (300029991,
  '01JAN2018'): Int64Index([29, 116, 125, 142, 247, 280, 320, 368, 436, 470, 472, 553, 554], dtype='int64'),
 (300030595,
  '01JAN2018'): Int64Index([ 58, 170, 186, 188, 194, 250, 271, 284, 313, 389, 398, 409, 412,
             438, 460, 498, 540],
            dtype='int64'),
 (300030922,
  '01JAN2018'): Int64Index([37, 80, 198, 204, 286, 302, 356, 414, 429, 455, 523, 535, 539], dtype='int64'),
 (300031505,
  '01JAN2018'): Int64Index([212, 230, 257, 303, 411, 544], dtype='int64'),
 (300031632,
  '01JAN2018'): Int64Index([13, 50, 53, 384, 453, 492, 508], dtype='int64'),
 (300032278, '01JAN2018'): Int64Index([145], dtype='int64'),
 (300033611, '01JAN2018'): Int64Index([21, 73, 176, 504], dtype='int64'),
 (300035210, '01JAN2018'): Int64Index([42, 102, 289], dtype='int64'),
 (300035544,
  '01JAN2018'): Int64Index([91, 99, 112, 151, 183, 199, 210, 259, 346, 352, 403, 452, 490, 505,
             513, 547],
            dtype='int64'),
 (300035697, '01JAN2018'): Int64Index([268, 288, 443, 497], dtype='int64'),
 (300036616,
  '01JAN2018'): Int64Index([ 24,  26,  76,  88, 171, 217, 222, 248, 256, 264, 291, 293, 324,
             338, 339, 378, 402, 415, 432, 474, 517, 519, 530, 537],
            dtype='int64'),
 (300036993,
  '01JAN2018'): Int64Index([60, 61, 214, 258, 300, 426, 442, 464, 501, 551], dtype='int64'),
 (300037151,
  '01JAN2018'): Int64Index([166, 211, 225, 251, 275, 376, 469], dtype='int64'),
 (300037465, '01JAN2018'): Int64Index([83, 96, 306], dtype='int64'),
 (300037734,
  '01JAN2018'): Int64Index([175, 354, 370, 387, 500, 521], dtype='int64'),
 (300037803,
  '01JAN2018'): Int64Index([57, 167, 192, 367, 401, 451, 510, 525, 528], dtype='int64'),
 (300038427, '01JAN2018'): Int64Index([153, 298], dtype='int64'),
 (300038658, '01JAN2018'): Int64Index([445], dtype='int64'),
 (300038778, '01JAN2018'): Int64Index([17, 30, 108], dtype='int64'),
 (300039129,
  '01JAN2018'): Int64Index([129, 148, 245, 253, 312, 336, 526], dtype='int64'),
 (300039321,
  '01JAN2018'): Int64Index([11, 45, 54, 63, 106, 195, 221, 228, 321, 323, 359, 379, 406, 489,
             533, 542, 552],
            dtype='int64'),
 (300039573, '01JAN2018'): Int64Index([512], dtype='int64'),
 (300040478,
  '01JAN2018'): Int64Index([5644, 5650, 5671, 5686, 5725, 5731, 5781, 5787, 5809, 5825, 5846,
             5865, 5890],
            dtype='int64'),
 (300043244,
  '01JAN2018'): Int64Index([5675, 5688, 5705, 5748, 5786, 5788, 5806, 5843], dtype='int64'),
 (300043245, '01JAN2018'): Int64Index([5699, 5743, 5807, 5829], dtype='int64'),
 (300043537, '01JAN2018'): Int64Index([5794, 5856, 5889], dtype='int64'),
 (300043575, '01JAN2018'): Int64Index([5870], dtype='int64'),
 (300043586, '01JAN2018'): Int64Index([5866], dtype='int64'),
 (300043611,
  '01JAN2018'): Int64Index([5654, 5663, 5681, 5685, 5702, 5717, 5768, 5893], dtype='int64'),
 (300043621,
  '01JAN2018'): Int64Index([5651, 5656, 5669, 5678, 5684, 5773, 5830, 5844, 5863, 5868], dtype='int64'),
 (300043773, '01JAN2018'): Int64Index([5680, 5753], dtype='int64'),
 (300043810, '01JAN2018'): Int64Index([5649], dtype='int64'),
 (300043835, '01JAN2018'): Int64Index([5778, 5848], dtype='int64'),
 (300043861,
  '01JAN2018'): Int64Index([5655, 5719, 5724, 5759, 5793, 5797], dtype='int64'),
 (300043974, '01JAN2018'): Int64Index([5735, 5798, 5836, 5897], dtype='int64'),
 (300044003, '01JAN2018'): Int64Index([5736, 5740, 5783], dtype='int64'),
 (300044204,
  '01JAN2018'): Int64Index([5645, 5666, 5715, 5723, 5745, 5770, 5780, 5810, 5820, 5840, 5883,
             5888],
            dtype='int64'),
 (300044215, '01JAN2018'): Int64Index([5827], dtype='int64'),
 (300044223,
  '01JAN2018'): Int64Index([5653, 5677, 5698, 5701, 5706, 5716, 5721, 5737, 5763, 5774, 5815,
             5821, 5845, 5854, 5871, 5874, 5877, 5886, 5892],
            dtype='int64'),
 (300044225, '01JAN2018'): Int64Index([5693, 5766, 5803, 5880], dtype='int64'),
 (300044321,
  '01JAN2018'): Int64Index([5648, 5707, 5709, 5720, 5726, 5742, 5746, 5826, 5834, 5851, 5858,
             5878, 5894, 5898, 5899],
            dtype='int64'),
 (300044364, '01JAN2018'): Int64Index([5674], dtype='int64'),
 (300044412, '01JAN2018'): Int64Index([5751], dtype='int64'),
 (300044437, '01JAN2018'): Int64Index([5741, 5802, 5838, 5842], dtype='int64'),
 (300044451, '01JAN2018'): Int64Index([5852], dtype='int64'),
 (300044577, '01JAN2018'): Int64Index([5785, 5805], dtype='int64'),
 (300044727, '01JAN2018'): Int64Index([5752, 5771, 5861], dtype='int64'),
 (300044728,
  '01JAN2018'): Int64Index([5659, 5672, 5682, 5687, 5690, 5710, 5712, 5713, 5718, 5727, 5750,
             5760, 5813, 5887],
            dtype='int64'),
 (300044736, '01JAN2018'): Int64Index([5668, 5670], dtype='int64'),
 (300044740,
  '01JAN2018'): Int64Index([5647, 5652, 5661, 5692, 5757, 5762, 5769, 5777, 5789, 5847, 5853,
             5860, 5875, 5879, 5891],
            dtype='int64'),
 (300044773, '01JAN2018'): Int64Index([5732, 5800], dtype='int64'),
 (300044800,
  '01JAN2018'): Int64Index([5667, 5676, 5683, 5758, 5765, 5811, 5816, 5823, 5835, 5850], dtype='int64'),
 (300044977, '01JAN2018'): Int64Index([5665, 5754], dtype='int64'),
 (300044988, '01JAN2018'): Int64Index([5694, 5744, 5812, 5831], dtype='int64'),
 (300044991, '01JAN2018'): Int64Index([5775], dtype='int64'),
 (300044992,
  '01JAN2018'): Int64Index([5643, 5673, 5691, 5695, 5722, 5734, 5747, 5756, 5795, 5801, 5824,
             5828, 5833, 5839, 5895],
            dtype='int64'),
 (300045031, '01JAN2018'): Int64Index([5764, 5822, 5862], dtype='int64'),
 (300045044, '01JAN2018'): Int64Index([5679], dtype='int64'),
 (300045058,
  '01JAN2018'): Int64Index([5646, 5660, 5767, 5784, 5792, 5808, 5859], dtype='int64'),
 (300045098, '01JAN2018'): Int64Index([5791, 5857], dtype='int64'),
 (300045217, '01JAN2018'): Int64Index([5867], dtype='int64'),
 (300045232,
  '01JAN2018'): Int64Index([5728, 5729, 5881, 5882, 5885], dtype='int64'),
 (300045235, '01JAN2018'): Int64Index([5658, 5714], dtype='int64'),
 (300045244, '01JAN2018'): Int64Index([5657, 5704, 5776, 5837], dtype='int64'),
 (300045254,
  '01JAN2018'): Int64Index([5700, 5711, 5733, 5738, 5799], dtype='int64'),
 (300045267,
  '01JAN2018'): Int64Index([5703, 5708, 5739, 5749, 5782, 5814, 5817, 5841, 5849, 5864, 5869,
             5872, 5884],
            dtype='int64'),
 (300045362, '01JAN2018'): Int64Index([5662, 5779], dtype='int64'),
 (300045377, '01JAN2018'): Int64Index([5818, 5896], dtype='int64'),
 (300045385, '01JAN2018'): Int64Index([5664, 5772], dtype='int64'),
 (300045473, '01JAN2018'): Int64Index([5796, 5804, 5855, 5873], dtype='int64'),
 (300045532, '01JAN2018'): Int64Index([5689, 5755, 5761, 5832], dtype='int64'),
 (300045536, '01JAN2018'): Int64Index([5697, 5876], dtype='int64'),
 (300045673, '01JAN2018'): Int64Index([5730, 5790], dtype='int64'),
 (300045681, '01JAN2018'): Int64Index([5696, 5819], dtype='int64'),
 (300045689,
  '01JAN2018'): Int64Index([5004, 5059, 5130, 5136, 5138, 5239, 5249, 5295, 5322, 5330, 5334,
             5342, 5353, 5368, 5386, 5393, 5502, 5505, 5517, 5555, 5558, 5587],
            dtype='int64'),
 (300045713, '01JAN2018'): Int64Index([5328, 5442], dtype='int64'),
 (300045715,
  '01JAN2018'): Int64Index([5194, 5320, 5361, 5493, 5594], dtype='int64'),
 (300045801,
  '01JAN2018'): Int64Index([5050, 5071, 5207, 5221, 5255, 5270, 5395, 5512, 5580], dtype='int64'),
 (300045818, '01JAN2018'): Int64Index([4996], dtype='int64'),
 (300045826,
  '01JAN2018'): Int64Index([4978, 5047, 5075, 5152, 5160, 5415, 5436, 5444], dtype='int64'),
 (300045864,
  '01JAN2018'): Int64Index([4964, 4973, 5056, 5090, 5102, 5128, 5178, 5302, 5337, 5435, 5457,
             5518, 5525],
            dtype='int64'),
 (300045930,
  '01JAN2018'): Int64Index([5034, 5275, 5382, 5418, 5488, 5642], dtype='int64'),
 (300046029,
  '01JAN2018'): Int64Index([4991, 5372, 5414, 5550, 5568], dtype='int64'),
 (300046058,
  '01JAN2018'): Int64Index([4956, 4988, 5074, 5077, 5089, 5105, 5132, 5150, 5153, 5157, 5184,
             5187, 5198, 5250, 5292, 5299, 5329, 5340, 5359, 5460, 5479, 5483,
             5487, 5494, 5500, 5537, 5589, 5605, 5609, 5613, 5632],
            dtype='int64'),
 (300046071, '01JAN2018'): Int64Index([4982, 5251, 5303, 5452], dtype='int64'),
 (300046131,
  '01JAN2018'): Int64Index([5000, 5225, 5296, 5379, 5528], dtype='int64'),
 (300046167, '01JAN2018'): Int64Index([5109], dtype='int64'),
 (300046186, '01JAN2018'): Int64Index([5129, 5229, 5360], dtype='int64'),
 (300046221,
  '01JAN2018'): Int64Index([4994, 5031, 5044, 5067, 5117, 5125, 5148, 5168, 5175, 5267, 5287,

In [258]:
i=0
for name, group in new_df1:
    print(name)
    print(group)
    i=i+1
    if i==5:
        break

(300010643, '01JAN2018')
      CoinIn  AccountNumber  AssetNumber  CoinOut  AvailableCompPoints  \
562     4784      300010643        20326     3080                    0
601     2400      300010643        20845     1400                    0
618     7240      300010643        20651     6250                    0
623     9484      300010643        20327     5415                    0
630     3450      300010643        21112     1150                    0
647    16830      300010643        21097    14830                    0
669     1080      300010643        20658       86                    0
689     1760      300010643        20433      330                    0
704     3290      300010643        20326     1075                    0
720      300      300010643        21106        0                    0
741     7216      300010643        20433     2570                    0
770     1040      300010643        20774       60                    0
790    10716      300010643        20676     5730                    0
801     4028      300010643        20326     2025                    0
817     2275      300010643        20072     1270                    0
825    11100      300010643        20432     6270                    0
830     4620      300010643        20064     3625                    0
864    12705      300010643        20845    10660                    0
903     1120      300010643        20651      130                    0
934     2024      300010643        20434      150                    0
966     5900      300010643        20839    10930                    0
977     7680      300010643        20659     6700                    0
1045    2570      300010643        21107      950                    0
1069    3770      300010643        21113     6260                    0
1070    3770      300010643        21099     2770                    0

      Slot Denomination TradingDate  HandlePulls  Location  IRSJackpot  \
562                 1.0   01JAN2018          158      3303           0
601                 1.0   01JAN2018           40       507           0
618                 1.0   01JAN2018          127      1705           0
623                 1.0   01JAN2018          148      3304           0
630                 2.0   01JAN2018           62      2309           0
647                 1.0   01JAN2018          284      2104           0
669                 1.0   01JAN2018           18      1712           0
689                 1.0   01JAN2018           20      2504           0
704                 1.0   01JAN2018          134      3303           0
720                 2.0   01JAN2018            7      1907           0
741                 1.0   01JAN2018           82      2504           0
770                 1.0   01JAN2018           26      1910           0
790                 1.0   01JAN2018          182      2507        1718
801                 1.0   01JAN2018          106      3303           0
817                 1.0   01JAN2018           76       710           0
825                 1.0   01JAN2018          240      2503        2363
830                 1.0   01JAN2018          109       702           0
864                 1.0   01JAN2018          227       507           0
903                 1.0   01JAN2018           28      1705           0
934                 1.0   01JAN2018           23      2505           0
966                 1.0   01JAN2018          102       501           0
977                 1.0   01JAN2018          107      1713           0
1045                2.0   01JAN2018           50      1908           0
1069                2.0   01JAN2018           67      2310           0
1070                2.0   01JAN2018           65      2106           0

           ...        GameProgressiveGroup  GameOptions GameBaseTheoPayTable  \
562        ...                           1            0                81.85
601        ...                           0            0                87.87
618        ...                           0            0                88.10
623        ...                           1            0                81.50
630        ...                           0            0                82.01
647        ...                           0            0                78.13
669        ...                           0            0                88.05
689        ...                           0            0                 0.00
704        ...                           1            0                81.85
720        ...                           0            0                82.01
741        ...                           0            0                 0.00
770        ...                           0            0                88.10
790        ...                           1            0                81.50
801        ...                           1            0                81.85
817        ...                           0            0                82.01
825        ...                           1            0                81.85
830        ...                           0            0                82.01
864        ...                           0            0                87.87
903        ...                           0            0                88.10
934        ...                           0            0                 0.00
966        ...                           0            0                 0.00
977        ...                           0            0                88.59
1045       ...                           0            0                82.01
1069       ...                           0            0                82.01
1070       ...                           0            0                82.01

     TimeCreated  DateCreated DateModified  TimeModified  Age  Gender  \
562      3:33:09    02JAN2018    02JAN2018       3:57:58   46       F
601     16:36:22    01JAN2018    01JAN2018      16:40:27   46       F
618     16:03:30    01JAN2018    01JAN2018      16:16:07   46       F
623      1:32:35    02JAN2018    02JAN2018       1:50:44   46       F
630      0:17:07    02JAN2018    02JAN2018       0:22:39   46       F
647      0:29:51    02JAN2018    02JAN2018       0:49:12   46       F
669     16:34:02    01JAN2018    01JAN2018      16:36:09   46       F
689     23:29:08    01JAN2018    01JAN2018      23:36:44   46       F
704      2:14:38    02JAN2018    02JAN2018       2:57:49   46       F
720      0:24:58    02JAN2018    02JAN2018       0:31:21   46       F
741     23:21:15    01JAN2018    01JAN2018      23:27:33   46       F
770     22:34:57    01JAN2018    01JAN2018      22:38:08   46       F
790     23:57:59    01JAN2018    02JAN2018       0:11:33   46       F
801      1:20:53    02JAN2018    02JAN2018       1:33:50   46       F
817      1:02:44    02JAN2018    02JAN2018       1:09:17   46       F
825     23:38:11    01JAN2018    01JAN2018      23:59:53   46       F
830      0:54:23    02JAN2018    02JAN2018       1:02:42   46       F
864     22:48:30    01JAN2018    01JAN2018      23:07:03   46       F
903     22:31:28    01JAN2018    01JAN2018      22:36:00   46       F
934     23:27:20    01JAN2018    01JAN2018      23:29:51   46       F
966     16:15:59    01JAN2018    01JAN2018      16:24:49   46       F
977     22:39:02    01JAN2018    01JAN2018      22:49:07   46       F
1045     0:21:41    02JAN2018    02JAN2018       0:24:55   46       F
1069     0:11:15    02JAN2018    02JAN2018       0:18:14   46       F
1070     0:49:15    02JAN2018    02JAN2018       0:55:53   46       F

      MembershipType
562                D
601                D
618                D
623                D
630                D
647                D
669                D
689                D
704                D
720                D
741                D
770                D
790                D
801                D
817                D
825                D
830                D
864                D
903                D
934                D
966                D
977                D
1045               D
1069               D
1070               D

[25 rows x 34 columns]
(300010751, '01JAN2018')
      CoinIn  AccountNumber  AssetNumber  CoinOut  AvailableCompPoints  \
800     5160      300010751        20439     2798                    0
803     4650      300010751        20439     1633                    0
883        0      300010751        20439     8360                    0
1032   16230      300010751        20439    12256                    0
1063    1320      300010751        20445     3433                    0

      Slot Denomination TradingDate  HandlePulls  Location  IRSJackpot  \
800                 1.0   01JAN2018          172      1104           0
803                 1.0   01JAN2018          155      1104           0
883                 1.0   01JAN2018            0      1104           0
1032                1.0   01JAN2018          515      1104           0
1063                1.0   01JAN2018           44      1110           0

           ...        GameProgressiveGroup  GameOptions GameBaseTheoPayTable  \
800        ...                           0            0                85.19
803        ...                           0            0                85.19
883        ...                           0            0                85.19
1032       ...                           0            0                85.19
1063       ...                           0            0                85.19

     TimeCreated  DateCreated DateModified  TimeModified  Age  Gender  \
800     17:53:35    01JAN2018    01JAN2018      18:30:12   70       F
803     18:49:54    01JAN2018    01JAN2018      19:03:40   70       F
883     18:47:44    01JAN2018    01JAN2018      18:50:08   70       F
1032    17:03:37    01JAN2018    01JAN2018      17:55:15   70       F
1063    19:51:52    01JAN2018    01JAN2018      20:00:06   70       F

      MembershipType
800                D
803                D
883                D
1032               D
1063               D

[5 rows x 34 columns]
(300010806, '01JAN2018')
      CoinIn  AccountNumber  AssetNumber  CoinOut  AvailableCompPoints  \
558     7480      300010806        20897     5640                    0
570     4500      300010806        20897     2768                    0
600     2260      300010806        20896     4370                    0
626     3489      300010806        20896     1082                    0
645      450      300010806        20896      129                    0
670      190      300010806        20896        0                    0
681     1335      300010806        20896      398                    0
700      765      300010806        22163       10                    0
710     2865      300010806        20897    11784                    0
748       80      300010806        20896        0                    0
753     4740      300010806        22156     3833                    0
758        0      300010806        20896       16                    0
853     3663      300010806        20896     8145                    0
858      810      300010806        22162      120                    0
867     3415      300010806        20897     1374                    0
868        0      300010806        20896        5                    0
876     6300      300010806        22159     3987                    0
892      595      300010806        20898       95                    0
894      535      300010806        20896       71                    0
899     2735      300010806        20897      984                    0
969      415      300010806        20896       36                    0
976     3555      300010806        22163     2075                    0
1049     645      300010806        20897        5                    0
1051    1425      300010806        20897      313                    0
1056       0      300010806        20897      457                    0
1089    1080      300010806        22156       80                    0

      Slot Denomination TradingDate  HandlePulls  Location  IRSJackpot  \
558                 1.0   01JAN2018          302      5103       13713
570                 1.0   01JAN2018          180      5103        1704
600                 1.0   01JAN2018           93      5102           0
626                 1.0   01JAN2018          171      5102           0
645                 1.0   01JAN2018           18      5102           0
670                 1.0   01JAN2018            9      5102           0
681                 1.0   01JAN2018           60      5102           0
700                 1.0   01JAN2018           11       108           0
710                 1.0   01JAN2018          116      5103           0
748                 1.0   01JAN2018            4      5102           0
753                 1.0   01JAN2018           78       101           0
758                 1.0   01JAN2018            0      5102           0
853                 1.0   01JAN2018          179      5102           0
858                 1.0   01JAN2018           12       103           0
867                 1.0   01JAN2018          137      5103           0
868                 1.0   01JAN2018            0      5102           0
876                 1.0   01JAN2018          119       102           0
892                 1.0   01JAN2018           22      5104           0
894                 1.0   01JAN2018           22      5102           0
899                 1.0   01JAN2018          110      5103           0
969                 1.0   01JAN2018           18      5102           0
976                 1.0   01JAN2018           76       108           0
1049                1.0   01JAN2018           26      5103           0
1051                1.0   01JAN2018           57      5103           0
1056                1.0   01JAN2018            0      5103           0
1089                1.0   01JAN2018           18       101           0

           ...        GameProgressiveGroup  GameOptions GameBaseTheoPayTable  \
558        ...                           0            0                  0.0
570        ...                           0            0                  0.0
600        ...                           0            0                  0.0
626        ...                           0            0                  0.0
645        ...                           0            0                  0.0
670        ...                           0            0                  0.0
681        ...                           0            0                  0.0
700        ...                           0            0                 88.1
710        ...                           0            0                  0.0
748        ...                           0            0                  0.0
753        ...                           0            0                 88.5
758        ...                           0            0                  0.0
853        ...                           0            0                  0.0
858        ...                           0            0                 88.1
867        ...                           0            0                  0.0
868        ...                           0            0                  0.0
876        ...                           0            0                 88.6
892        ...                           0            0                  0.0
894        ...                           0            0                  0.0
899        ...                           0            0                  0.0
969        ...                           0            0                  0.0
976        ...                           0            0                 88.1
1049       ...                           0            0                  0.0
1051       ...                           0            0                  0.0
1056       ...                           0            0                  0.0
1089       ...                           0            0                 88.5

     TimeCreated  DateCreated DateModified  TimeModified  Age  Gender  \
558     17:35:48    01JAN2018    01JAN2018      18:13:50   64       F
570     18:41:50    01JAN2018    01JAN2018      18:58:52   64       F
600     19:10:13    01JAN2018    01JAN2018      19:26:01   64       F
626     18:27:48    01JAN2018    01JAN2018      18:43:35   64       F
645     19:30:31    01JAN2018    01JAN2018      19:33:45   64       F
670     18:12:06    01JAN2018    01JAN2018      18:13:50   64       F
681     18:15:35    01JAN2018    01JAN2018      18:20:55   64       F
700     22:08:33    01JAN2018    01JAN2018      22:12:09   64       F
710     21:40:20    01JAN2018    01JAN2018      22:09:55   64       F
748     18:57:49    01JAN2018    01JAN2018      18:58:52   64       F
753     22:17:16    01JAN2018    01JAN2018      22:26:02   64       F
758     19:09:21    01JAN2018    01JAN2018      19:10:16   64       F
853     19:42:07    01JAN2018    01JAN2018      20:14:05   64       F
858     17:20:18    01JAN2018    01JAN2018      17:22:52   64       F
867     19:33:04    01JAN2018    01JAN2018      19:42:54   64       F
868     19:29:08    01JAN2018    01JAN2018      19:30:45   64       F
876     17:21:26    01JAN2018    01JAN2018      17:34:31   64       F
892     21:34:33    01JAN2018    01JAN2018      21:42:15   64       F
894     19:26:26    01JAN2018    01JAN2018      19:30:44   64       F
899     18:19:54    01JAN2018    01JAN2018      18:28:01   64       F
969     19:03:59    01JAN2018    01JAN2018      19:05:56   64       F
976     22:10:41    01JAN2018    01JAN2018      22:19:18   64       F
1049    18:13:17    01JAN2018    01JAN2018      18:16:01   64       F
1051    19:05:13    01JAN2018    01JAN2018      19:10:16   64       F
1056    18:12:37    01JAN2018    01JAN2018      18:13:50   64       F
1089    22:25:18    01JAN2018    01JAN2018      22:28:15   64       F

      MembershipType
558                C
570                C
600                C
626                C
645                C
670                C
681                C
700                C
710                C
748                C
753                C
758                C
853                C
858                C
867                C
868                C
876                C
892                C
894                C
899                C
969                C
976                C
1049               C
1051               C
1056               C
1089               C

[26 rows x 34 columns]
(300010986, '01JAN2018')
      CoinIn  AccountNumber  AssetNumber  CoinOut  AvailableCompPoints  \
708    79950      300010986        20476    68150                    0
823    59425      300010986        21075    50425                    0
1085  137280      300010986        21074   134020                    0
1091       0      300010986        21075        5                    0
1099    5700      300010986        20472     6460                    0
1104   28200      300010986        21080     8200                    0

      Slot Denomination TradingDate  HandlePulls  Location  IRSJackpot  \
708                 1.0   01JAN2018          533      1313           0
823                 1.0   01JAN2018          467      1303           0
1085                1.0   01JAN2018         1571      1302           0
1091                1.0   01JAN2018            0      1303           0
1099                1.0   01JAN2018           95      1309           0
1104                1.0   01JAN2018          188      1308           0

           ...        GameProgressiveGroup  GameOptions GameBaseTheoPayTable  \
708        ...                           0            0                  0.0
823        ...                           0            0                  0.0
1085       ...                           0            0                  0.0
1091       ...                           0            0                  0.0
1099       ...                           0            0                  0.0

In [252]:
df.index.get_level_values(0)

Int64Index([300010643, 300010643, 300010643, 300010643, 300010643, 300010643,
            300010643, 300010643, 300010643, 300010643,
            ...
            300204957, 300204957, 300204957, 300204957, 300204957, 300204957,
            300204957, 300204957, 300207231, 300207231],
           dtype='int64', name='AccountNumber', length=10000)

In [213]:
df3 = pd.DataFrame({'X' : ['A', 'B', 'A', 'B'], 'Y' : [1, 4, 3, 2]})

In [214]:
df3

   X  Y
0  A  1
1  B  4
2  A  3
3  B  2

In [239]:
df4 = df3.groupby(['X','Y'])

In [240]:
df4.groups

{('A', 1): Int64Index([0], dtype='int64'),
 ('A', 3): Int64Index([2], dtype='int64'),
 ('B', 2): Int64Index([3], dtype='int64'),
 ('B', 4): Int64Index([1], dtype='int64')}

In [228]:
for i in df4.groups:
        print(i)

A
B